/** The MCP server's instructions for the agent (part of what the agent sees, so part of the tools fingerprint). */
export const INSTRUCTIONS = [
  'jev-browser drives a real Chrome browser with JEV, a fast decision model (TypeSafe System One). JEV does not write text or plan:',
  'you plan and supply the data; JEV finds elements, reads page state and verifies steps in ~100 ms per decision.',
  'Prefer jev_task for multi-step goals: goal, about and hints in English, param values exactly as the site shows them, dates as',
  'YYYY-MM-DD or {from,to}, secrets as params with secret:true, and result {select: "min(price)"} when the task should end on results:',
  'JEV sorts on the site and hands you the results list (one line per item); you read it and pick the answer yourself.',
  'The task runs in the background (consent banners, prefilled fields, autocompletes, date pickers, results in new tabs are handled);',
  'reversible steps (fields, filter chips, dropdowns, pickers, sorting) try the best candidate even at low confidence, verify the effect and',
  'roll back before trying the next (policy.confidence.trial); when that runs out, or before anything irreversible, JEV asks you a question',
  'instead of guessing. For goals that take several parts of a site, pass `plan`: milestones [{do, done_when}] in English from what',
  'you know about the site; JEV aims at the current one and checks each done_when on the page. When a task is stuck it sends a',
  '`consult` question with a situation report and keeps exploring safe steps meanwhile: answer with a plan, a hint (scope "domain"',
  'keeps it for the site), goto (url) or pick; a consult it no longer needs is withdrawn. Questions arrive as <channel source="jev-browser" task_id=… question_id=…>',
  'events (Claude Code with channels), as "JEV is waiting for your answer" blocks appended to every jev tool result, and through jev_wait.',
  'In Claude Code, run `jev watch <task_id>` in the background after starting a task: it exits on the next question or when the task ends.',
  'Answer with jev_answer. Blocker questions (CAPTCHA, login wall) need a person: ask the user to solve it in the browser, then answer',
  '"continue"; if the tab is headless, abort and rerun with driver "extension" (the user\'s Chrome). Confirm risk_confirm questions only if',
  'the user asked for that action. For direct control use jev_observe (compact page view), jev_find (JEV-ranked search), jev_ask',
  '(your own typed questions) and jev_act. Setup problems: jev_doctor.',
].join(' ');
